name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x86_64
            ext: x86_64-apple-darwin
          - os: macos-latest
            arch: arm64
            ext: arm64-apple-darwin
          - os: ubuntu-latest
            arch: amd64
            platform: linux/amd64
            ext: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            arch: arm64
            platform: linux/arm64
            ext: arm64-unknown-linux-musl
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the static binary
        run: docker buildx build --platform ${{ matrix.platform }} --tag crystalline:latest .
      - name: Extract the static binary
        run: docker cp $(docker create --platform ${{ matrix.platform }} crystalline:latest):/crystalline ./crystalline
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: crystalline_${{ matrix.ext }}
          path: ./crystalline
